### PR TITLE
Updated dependencies and bumped node requirement

### PR DESCRIPTION
**Pull request by tylerconstance**
Updated packages with `npm-check-updates -u` and manually set `"node": ">=12"` since some of the major version upgrades dropped support for node@10

### CODE REVIEW

**Review by devinivy — APPROVED** [review]
Yay :)

**Comment by derekwheee** [comment]
Should the Travis config be updated as well?
https://github.com/BigRoomStudios/strangeluv/blob/strangeluv/.travis.yml#L4

**Comment by devinivy** [comment]
Yeah, good call!

**Review by wswoodruff — APPROVED** [review]
Looks good

🗳🏃

**Pull request merged**
