### PR TITLE
taking out bootstrap classes that we're not using anymore

### PR DESCRIPTION
**Pull request by rbkh**
🙏 RIP bootstrap

### CODE REVIEW

**Comment by devinivy** [comment]
What about the line(s) that include bootstrap in the project?

**Comment by rbkh** [comment]
That was already removed, I'm just cleaning up now-useless classes

**Comment by devinivy** [comment]
Sweet, then I think the tests just need updating https://github.com/BigRoomStudios/strangeluv/blob/c460f6a90c61b9631d9bcaf3557293e777871e85/tests/components/Counter/Counter.spec.js

**Comment by rbkh** [comment]
I actually just found that! cleaning up now.

**Pull request merged**
